import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {profileSchema,participant,matchKey,validOrigin,validatePng,readBounded} from '../lib/domain.ts';
const p={name:'Vick',course:'Engenharia de Software',semester:6,age:22,bio:'Olá',interests:['Games'],intent:'Conhecer pessoas',consent:true};
test('valid profile accepted',()=>assert.equal(profileSchema.parse(p).name,'Vick'));
for(const [name,change] of Object.entries({minor:{age:17},semester:{semester:0},course:{course:'fake'},consent:{consent:false},overlong:{bio:'a'.repeat(401)},privilege:{approved:1},identity:{id:'another-user'},interests:{interests:Array(25).fill('a')}}))test('reject '+name,()=>assert.equal(profileSchema.safeParse({...p,...change}).success,false));
test('match stable in either direction',()=>assert.equal(matchKey('a','b'),matchKey('b','a')));
test('IDOR denied',()=>{assert.equal(participant({a:'a',b:'b'},'c'),false);assert.equal(participant(null,'a'),false);assert.equal(participant({a:'a',b:'b'},'a'),true)});
test('CSRF cross origin and missing origin denied',()=>{assert.equal(validOrigin(new Request('https://app.test/api',{headers:{Origin:'https://evil.test'}})),false);assert.equal(validOrigin(new Request('https://app.test/api')),false);assert.equal(validOrigin(new Request('https://app.test/api',{headers:{Origin:'https://app.test'}})),true)});
test('PNG real icon accepted, corruption and appended payload denied',async()=>{const b=new Uint8Array(await readFile('public/icon-192.png'));assert.equal(validatePng(b),true);const c=b.slice();c[50]^=1;assert.equal(validatePng(c),false);assert.equal(validatePng(new Uint8Array([...b,1])),false);assert.equal(validatePng(new TextEncoder().encode('<svg onload=alert(1)>')),false)});
test('streaming body bounded without content length',async()=>{await assert.rejects(readBounded(new Request('https://a.test',{method:'POST',body:'123456'}),5),RangeError);assert.equal((await readBounded(new Request('https://a.test',{method:'POST',body:'1234'}),5)).length,4)});

test('expanded interests accept 24 choices and long movie titles, but bound individual length',()=>{assert.equal(profileSchema.safeParse({...p,interests:Array.from({length:24},(_,i)=>'Hobby '+i)}).success,true);assert.equal(profileSchema.safeParse({...p,interests:['Filme: Três Homens, um Destino']}).success,true);assert.equal(profileSchema.safeParse({...p,interests:['a'.repeat(81)]}).success,false);});
