import {sqliteTable,text,integer,primaryKey,index} from 'drizzle-orm/sqlite-core';
export const profiles=sqliteTable('profiles',{id:text('id').primaryKey(),name:text('name').notNull(),course:text('course').notNull(),semester:integer('semester').notNull(),age:integer('age').notNull(),bio:text('bio').notNull(),interests:text('interests').notNull(),intent:text('intent').notNull(),photo:text('photo'),approved:integer('approved').notNull().default(0),paused:integer('paused').notNull().default(0),consentAt:text('consent_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('profile_discovery').on(t.approved,t.paused,t.course)]);
export const reactions=sqliteTable('reactions',{sender:text('sender').notNull().references(()=>profiles.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>profiles.id,{onDelete:'cascade'}),kind:text('kind').notNull()},t=>[primaryKey({columns:[t.sender,t.target]})]);
export const matches=sqliteTable('matches',{id:text('id').primaryKey(),a:text('a').notNull().references(()=>profiles.id,{onDelete:'cascade'}),b:text('b').notNull().references(()=>profiles.id,{onDelete:'cascade'}),createdAt:text('created_at').notNull()});
export const messages=sqliteTable('messages',{id:text('id').primaryKey(),matchId:text('match_id').notNull().references(()=>matches.id,{onDelete:'cascade'}),sender:text('sender').notNull(),body:text('body').notNull(),createdAt:text('created_at').notNull()},t=>[index('messages_match').on(t.matchId,t.createdAt)]);
export const blocks=sqliteTable('blocks',{sender:text('sender').notNull().references(()=>profiles.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>profiles.id,{onDelete:'cascade'})},t=>[primaryKey({columns:[t.sender,t.target]})]);
export const reports=sqliteTable('reports',{id:text('id').primaryKey(),sender:text('sender').notNull().references(()=>profiles.id,{onDelete:'cascade'}),target:text('target').notNull().references(()=>profiles.id,{onDelete:'cascade'}),reason:text('reason').notNull(),createdAt:text('created_at').notNull(),resolved:integer('resolved').notNull().default(0)});
export const limits=sqliteTable('limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),target:text('target').notNull(),createdAt:text('created_at').notNull()});
