plugins { id 'com.android.application' }
android {
 namespace 'br.edu.unilins.unimatch'
 compileSdk 35
 defaultConfig {
  applicationId 'br.edu.unilins.unimatch'
  minSdk 26
  targetSdk 35
  versionCode 2
  versionName '0.2.0-pilot'
 }
 buildTypes { release { minifyEnabled false } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
